#include "ui/headers/menudef.h"
#include "ui/includes/common.inc"

#define 	LAYOUT_SEPATATOR_1		25
#define 	LAYOUT_SEPATATOR_2		32

#define LAYOUT_X_START			-298
#define LAYOUT_Y_START			15

#define STYLE_PC				1

#include "ui/includes/style.inc"
#include "ui/includes/components/layout.inc"

#undef LAYOUT_TEXT_OFFSET_X
#define LAYOUT_TEXT_OFFSET_X 	0

#undef LAYOUT_HORIZONTAL_ALIGN
#define LAYOUT_HORIZONTAL_ALIGN HORIZONTAL_ALIGN_CENTER

#undef	LAYOUT_X_SPACING
#define LAYOUT_X_SPACING 		310

#undef	LAYOUT_Y_COUNT
#define LAYOUT_Y_COUNT 			15

#undef	LAYOUT_SIZE_X
#define LAYOUT_SIZE_X 			160

#undef SR_BTN_SIZE_X
#define SR_BTN_SIZE_X 			280

#undef	LAYOUT_SIZE_Y
#define LAYOUT_SIZE_Y 			22

#undef 	SR_BTN_APPLY_X
#define SR_BTN_APPLY_X 			240

#undef 	SR_BTN_APPLY_Y
#define SR_BTN_APPLY_Y 			-100

#undef LAYOUT_SEPATATOR_1
#define LAYOUT_SEPATATOR_1            0
